name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_BOT_SECRET_KEY }}
          DATABASE_PR_ID: ${{ secrets.DATABASE_PR_ID }}
          DATABASE_PR_STATE_ID: ${{ secrets.DATABASE_PR_STATE_ID }}
        with:
          left_delimiter: ']('
          right_delimiter: ')'
          notion_properties: '{ "status":{ "name":"Notion Status" }, "pull_request":{ "name":"Pull Request", "relation":{ "id":"Number", "link":"Link", "state":"State", "title":"Title" } }, "pull_request_state":{ "name":"Name", "event_type":"Event" } }'
          opened: 'Code Review'
          ready_for_review: 'Code Review'
          closed: 'Completed'
          merged: 'Completed'
