name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run build
          npm run package
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_BOT_SECRET_KEY }}
          DATABASE_PR_ID: ${{ secrets.DATABASE_PR_ID }}
          DATABASE_PR_STATE_ID: ${{ secrets.DATABASE_PR_STATE_ID }}
        with:
          left_delimiter: ']('
          right_delimiter: ')'
          notion_status_property: 'Notion Status'
          notion_pr_property_name: 'Pull Request'
          notion_pr_id_column_name: 'Number'
          opened: 'In review'
          ready_for_review: 'In review'
          closed: 'Completed'
          merged: 'Completed'
